"""
attack_chain_detection.py
--------------------------
Detects the multi-stage attack chain generated by attack_chain_simulation.py.

This module deliberately does NOT reimplement Project 4's brute-force /
event-storage logic -- it imports `detection_rules` and `siem_ingest`
directly from `04-soc-siem-lab/` and builds three new, chain-specific rules
on top of them:

  1. detect_successful_brute_force()  -- correlates a Project-4 brute-force
     alert with an auth_success from the SAME source IP shortly after, using
     a username that appeared among the failed attempts. This is the
     "the attacker's guess eventually worked" signal.
     MITRE: T1110 (Brute Force) -> T1078 (Valid Accounts)

  2. detect_lateral_movement()  -- for a username just flagged as
     compromised, looks for auth_success events on OTHER hosts within a
     short window afterward. Generic: it works off any (username,
     compromise_timestamp, initial_host) tuple, not a hardcoded name.
     MITRE: T1021.004 (Remote Services: SSH)

  3. detect_exfiltration()  -- flags data_exfil events whose byte count
     exceeds a volumetric threshold. Generic: operates on the data_exfil
     event type Project 4's siem_ingest.py now supports, not on this
     scenario's specific numbers.
     MITRE: T1041 (Exfiltration Over C2 Channel)

detect_attack_chain() then correlates all three into one incident-level
alert only when all stages tie together in sequence for the same identity,
which is the actual "multi-stage" detection this capstone demonstrates.
"""

import os
import sqlite3
import sys
from datetime import datetime, timedelta, timezone

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "04-soc-siem-lab"))
import detection_rules  # noqa: E402 (Project 4 module, reused not duplicated)
import siem_ingest  # noqa: E402

# --- Stage 1b: successful login shortly after a flagged brute-force burst --
# Rationale: a burst that stops right before a success, from the same
# source IP, within a short follow-on window, is the standard "credential
# stuffing paid off" pattern -- real attack tooling logs in immediately
# once a valid combination is found, typically within seconds to a couple
# of minutes (allowing for tool restart / manual follow-up).
SUCCESS_AFTER_BURST_WINDOW_MINUTES = 5

# --- Stage 2: lateral movement -----------------------------------------
# Rationale: once an account is confirmed compromised, any successful login
# by that same account to a *different* host shortly after is inherently
# suspicious regardless of source IP, because the compromise timestamp is
# already established ground truth -- unlike Project 4's generic rules,
# this one is intentionally identity-scoped rather than volume-scoped.
LATERAL_MOVEMENT_WINDOW_MINUTES = 30
LATERAL_MOVEMENT_MIN_HOSTS = 2

# --- Stage 3: exfiltration -----------------------------------------------
# Rationale: routine application/DB traffic on this simulated estate is at
# most a few MB per connection (per the baseline traffic generated by
# Project 4's log_generator.generate_baseline, which emits no data_exfil
# events at all). 100 MB in one flow is a conservative floor for "this is
# not routine" -- well above interactive traffic, well below what a
# legitimate nightly backup job would look like (which should instead be
# allow-listed by host/schedule in a real deployment, see README caveats).
EXFIL_BYTES_THRESHOLD = 100_000_000

MITRE_MAP = {
    "brute_force": {"id": "T1110", "name": "Brute Force", "tactic": "Credential Access"},
    "valid_accounts": {"id": "T1078", "name": "Valid Accounts", "tactic": "Initial Access"},
    "lateral_movement": {"id": "T1021.004", "name": "Remote Services: SSH", "tactic": "Lateral Movement"},
    "exfiltration": {"id": "T1041", "name": "Exfiltration Over C2 Channel", "tactic": "Exfiltration"},
}


def _parse_ts(ts: str) -> datetime:
    return datetime.fromisoformat(ts)


def detect_successful_brute_force(conn: sqlite3.Connection,
                                   window_minutes: int = SUCCESS_AFTER_BURST_WINDOW_MINUTES) -> list[dict]:
    """Reuses Project 4's detect_brute_force() to find the bursts, then adds
    the one correlation Project 4 doesn't do: did a login succeed from that
    same IP afterward, using one of the attempted usernames?"""
    bursts = detection_rules.detect_brute_force(conn)
    window = timedelta(minutes=window_minutes)
    results = []

    for burst in bursts:
        src_ip = burst["src_ip"]
        burst_end = _parse_ts(burst["window_end"])
        tried_usernames = set(burst["usernames_attempted"])

        rows = conn.execute(
            """SELECT timestamp, host, username FROM events
               WHERE event_type = 'auth_success' AND src_ip = ?
               ORDER BY timestamp""",
            (src_ip,),
        ).fetchall()

        for r in rows:
            ts = _parse_ts(r["timestamp"])
            if burst_end <= ts <= burst_end + window and r["username"] in tried_usernames:
                results.append({
                    "rule": "brute_force_success",
                    "severity": "critical",
                    "src_ip": src_ip,
                    "username": r["username"],
                    "initial_access_host": r["host"],
                    "brute_force_window": (burst["window_start"], burst["window_end"]),
                    "compromise_timestamp": r["timestamp"],
                    "mitre": [MITRE_MAP["brute_force"], MITRE_MAP["valid_accounts"]],
                    "detail": (f"Account '{r['username']}' authenticated successfully from "
                               f"{src_ip} to {r['host']} at {r['timestamp']}, "
                               f"{(ts - burst_end).total_seconds():.0f}s after a {burst['event_count']}"
                               f"-attempt brute-force burst from the same IP ended -- credential "
                               f"compromise confirmed (T1110 -> T1078)."),
                })
                break  # one confirmed compromise per burst is enough evidence
    return results


def detect_lateral_movement(conn: sqlite3.Connection, username: str,
                             after_timestamp: str, initial_host: str,
                             window_minutes: int = LATERAL_MOVEMENT_WINDOW_MINUTES,
                             min_hosts: int = LATERAL_MOVEMENT_MIN_HOSTS) -> dict | None:
    after_ts = _parse_ts(after_timestamp)
    window = timedelta(minutes=window_minutes)

    rows = conn.execute(
        """SELECT timestamp, host, src_ip FROM events
           WHERE event_type = 'auth_success' AND username = ? AND timestamp > ?
           ORDER BY timestamp""",
        (username, after_timestamp),
    ).fetchall()

    hops = [r for r in rows
            if r["host"] != initial_host and _parse_ts(r["timestamp"]) <= after_ts + window]
    distinct_hosts = sorted({r["host"] for r in hops})

    if len(distinct_hosts) < min_hosts:
        return None

    return {
        "rule": "lateral_movement",
        "severity": "critical",
        "username": username,
        "pivot_from_host": initial_host,
        "hosts_reached": distinct_hosts,
        "events": [{"timestamp": r["timestamp"], "host": r["host"], "src_ip": r["src_ip"]} for r in hops],
        "mitre": [MITRE_MAP["lateral_movement"]],
        "detail": (f"Account '{username}' (already flagged compromised on {initial_host}) "
                   f"authenticated to {len(distinct_hosts)} additional hosts "
                   f"({', '.join(distinct_hosts)}) within {window_minutes} minutes of the "
                   f"initial compromise -- consistent with SSH-based lateral movement (T1021.004)."),
    }


def detect_exfiltration(conn: sqlite3.Connection,
                         candidate_hosts: list[str] | None = None,
                         after_timestamp: str | None = None,
                         threshold_bytes: int = EXFIL_BYTES_THRESHOLD) -> list[dict]:
    query = "SELECT timestamp, host, src_ip, dst_ip, dst_port, bytes_transferred FROM events " \
            "WHERE event_type = 'data_exfil' AND bytes_transferred >= ?"
    params: list = [threshold_bytes]
    if after_timestamp:
        query += " AND timestamp > ?"
        params.append(after_timestamp)
    query += " ORDER BY timestamp"

    rows = conn.execute(query, params).fetchall()
    results = []
    for r in rows:
        if candidate_hosts and r["host"] not in candidate_hosts:
            continue
        results.append({
            "rule": "exfiltration",
            "severity": "critical",
            "host": r["host"],
            "src_ip": r["src_ip"],
            "dst_ip": r["dst_ip"],
            "dst_port": r["dst_port"],
            "bytes_transferred": r["bytes_transferred"],
            "timestamp": r["timestamp"],
            "mitre": [MITRE_MAP["exfiltration"]],
            "detail": (f"{r['bytes_transferred'] / 1_000_000:.1f} MB outbound transfer from "
                       f"{r['host']} ({r['src_ip']}) to {r['dst_ip']}:{r['dst_port']} at "
                       f"{r['timestamp']} -- exceeds {threshold_bytes / 1_000_000:.0f} MB "
                       f"volumetric threshold (T1041)."),
        })
    return results


def detect_attack_chain(conn: sqlite3.Connection) -> list[dict]:
    """Top-level correlation: only raises a chain-level alert when Stage 1
    (compromise) -> Stage 2 (lateral movement) -> Stage 3 (exfiltration)
    all tie together for the SAME identity in sequence. Also returns the
    individual stage alerts, since a real SOC would want both the granular
    detections and the correlated incident view."""
    chain_alerts = []
    stage1_events = detect_successful_brute_force(conn)

    for stage1 in stage1_events:
        stage2 = detect_lateral_movement(
            conn, username=stage1["username"],
            after_timestamp=stage1["compromise_timestamp"],
            initial_host=stage1["initial_access_host"],
        )
        if not stage2:
            continue

        candidate_hosts = [stage1["initial_access_host"]] + stage2["hosts_reached"]
        stage3_list = detect_exfiltration(
            conn, candidate_hosts=candidate_hosts,
            after_timestamp=stage2["events"][0]["timestamp"],
        )
        if not stage3_list:
            continue

        chain_alerts.append({
            "rule": "multi_stage_attack_chain",
            "severity": "critical",
            "username": stage1["username"],
            "attacker_ip": stage1["src_ip"],
            "stage1_initial_access": stage1,
            "stage2_lateral_movement": stage2,
            "stage3_exfiltration": stage3_list,
            "mitre_chain": [MITRE_MAP["brute_force"], MITRE_MAP["valid_accounts"],
                             MITRE_MAP["lateral_movement"], MITRE_MAP["exfiltration"]],
            "detail": (f"Full attack chain detected for account '{stage1['username']}': "
                       f"brute force from {stage1['src_ip']} -> valid-account login on "
                       f"{stage1['initial_access_host']} -> lateral movement to "
                       f"{', '.join(stage2['hosts_reached'])} -> "
                       f"{len(stage3_list)} exfiltration event(s) totalling "
                       f"{sum(s['bytes_transferred'] for s in stage3_list) / 1_000_000:.1f} MB."),
        })

    return chain_alerts


def persist_chain_alerts(conn: sqlite3.Connection, chain_alerts: list[dict]) -> list[str]:
    ids = []
    now = datetime.now(timezone.utc).isoformat()
    for i, c in enumerate(chain_alerts):
        alert_id = f"CHAIN-{i+1:03d}"
        conn.execute(
            """INSERT OR REPLACE INTO alerts
               (alert_id, rule, severity, src_ip, target, window_start, window_end,
                event_count, detail, created_at)
               VALUES (?,?,?,?,?,?,?,?,?,?)""",
            (alert_id, c["rule"], c["severity"], c["attacker_ip"], c["username"],
             c["stage1_initial_access"]["compromise_timestamp"],
             c["stage3_exfiltration"][-1]["timestamp"],
             3 + len(c["stage2_lateral_movement"]["hosts_reached"]), c["detail"], now),
        )
        ids.append(alert_id)
    conn.commit()
    return ids


if __name__ == "__main__":
    here = os.path.dirname(__file__)
    db_path = os.path.join(here, "data", "attack_chain.db")
    conn = siem_ingest.get_connection(db_path)

    chains = detect_attack_chain(conn)
    ids = persist_chain_alerts(conn, chains)

    print(f"Detected {len(chains)} multi-stage attack chain(s):\n")
    for alert_id, c in zip(ids, chains):
        print(f"[{alert_id}] {c['detail']}\n")
        print("  MITRE ATT&CK mapping:")
        for m in c["mitre_chain"]:
            print(f"    {m['id']:<12} {m['name']:<28} ({m['tactic']})")
        print()

    conn.close()
